# Generated by Django 2.2.24 on 2021-06-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedmeal',
            name='price',
        ),
    ]
