# Generated by Django 2.2.24 on 2021-06-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210613_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='orderedmeal',
            name='quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
